### ISSUE TITLE
Angular 1.3 support?

### ISSUE THREAD

**Issue by heycalmdown** [witq/ng-transiterate#3]
Is this module can be worked with Angular 1.3 properly?

**Comment by witq** [comment]
I just checked against 1.3.12 and it works fine for me. Please provide more details.

**Comment by heycalmdown** [comment]
I know. It works perfectly with below option at my `bower.json`

```json
{
  "ng-transiterate": "1.1.2",
  "angular": ">= 1.3.0"
}
```

However, what I meant is that your `bower.json` could be fixed with

```json
{
  "dependencies": {
    "angular": "~1.3"
  }
}
```

**Comment by witq** [comment]
I'm glad to hear it works for you. Is the project you're working on publicly available so I could take a look?

As for the dependency declaration, wouldn't that mean that it requires angular 1.3? That's clearly not the case so I think that would be misleading. I'll look into it.

**Comment by heycalmdown** [comment]
I added a line with `resolution` to make it more clear. It is working because I forced resolution of version conflict on that line. Not a good one.

And, no, it is not a public one. That is a commercial project, which target to end of this year. Sorry.

**Comment by witq** [comment]
OMG, finally, fixed it. Thank you.
